# => inherits: generic <= #

awesome_wm:
  theme:
    name: powerline
    wallpaper: /data/pics/wall.jpg
  widgets:
    audio:
    clock:
    cpu:
    disk:
    memory:
    network:
    temperature:
  font:
    name: Hack
    size:
      popup: 9
      main:  10

terminal:
  cmd: urxvtc -e /bin/zsh -c screen
  noscreen: urxvtc

web_browser:
  cmd: firefox

features:
  - copyq
  - firefox
  - gimp
  - mega
  - mplayer
  - tor
  - zathura

# vim: set filetype=yaml :
