# => inherits: generic <= #

awesome_wm:
  theme:
    name: powerline
    wallpaper: /data/pics/wall.jpg
  widgets:
    audio:
    clock:
    cpu:
    disk:
    memory:
    network:
    temperature:
  font:
    name: Monospace
    size:
      popup: 9
      main:  10

terminal:
  cmd: urxvt256c -e /bin/zsh -c 'tmux -2'
  noscreen: urxvt256c

web_browser:
  cmd: firefox

features:
  - cmus
  - copyq
  - firefox
  - gimp
  - mega
  - mplayer
  - rofi
  - spotify
  - tor
  - zathura

# vim: set filetype=yaml :
